### ISSUE TITLE
A-star key error

### ISSUE THREAD

**Issue by mozerfazer** [mozerfazer/PubMedConceptAnalysis#4]
Should we pass the name of the concept or the id?
Try it with a big corpus, we get a key error. 
Also, now we have both the cosine and KL similarities. There should be the possibility of calling A-star with either of the 2 similarity functions.

**Comment by Falitokiniaina** [comment]
when calling a_star(self, source, target), source and target should be id. 
It is exactly like an.a_star(an.getIdFromConcept(concept1_source)[0][0],  an.getIdFromConcept(concept2_target)[0][0]).

**Comment by mozerfazer** [comment]
fixed
